apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: home-assistant
    spec:
      automountServiceAccountToken: true
      initContainers:
        - name: config-data
          image: ubuntu:xenial
          command: ["/bin/sh","-c"]
          args: ["cp /etc/config/configuration.yaml /config/configuration.yaml; touch /config/scripts.yaml; touch /config/automations.yaml; touch /config/scenes.yaml"]
          volumeMounts:
          - mountPath: /config
            name: config-dir
          - mountPath: /etc/config
            name: injected-config-dir
      containers:
      - env:
        - name: TZ
          value: UTC
        image: ghcr.io/home-assistant/home-assistant:2022.5.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        name: home-assistant
        ports:
        - containerPort: 8123
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        startupProbe:
          failureThreshold: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config-dir
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-dir
        hostPath: 
          path: /config
          type: DirectoryOrCreate
      - name: injected-config-dir
        projected:
          sources:
          - configMap:
              items:
              - key: home-assistant-config
                path: configuration.yaml
              name: home-assistant-config
